repos:
  - repo: local
    hooks:
      - id: ruff-lint
        name: ruff lint
        entry: mise x -- ruff check --fix
        language: system
        types: [python]

      - id: ruff-format
        name: ruff format
        entry: mise x -- ruff format
        language: system
        types: [python]

      - id: mypy
        name: mypy
        entry: mise x -- uv run mypy src/
        language: system
        types: [python]
        pass_filenames: false
